### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jeremytubbs** [sgf-aws/aws-ecs-demo-laravel#1]
I cannot find the references docker or aws files:
- aws/laravel-rds.yml
- aws/laravel-ecr.yml
- aws/laravel-ecs.yml
- ./docker/up.sh
- ./docker/push.sh
- ./docker/down.sh
- ./docker/logs.sh

**Comment by Alec13355** [comment]
https://github.com/sgf-aws/aws-ecs-docker-laravel-django
Check out this repo. Seems like there was a fork at some time and these are the same readMEs but with different files.

**Comment by isbkch** [comment]
I've added a PR with the missing files https://github.com/sgf-aws/aws-ecs-demo-laravel/pull/5
